trigger:
- main

pool:
  name: Default

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: Install Node.js

# Frontend install
- script: |
    cd frontend
    npm install --legacy-peer-deps
  displayName: Install frontend dependencies

# Backend install
- script: |
    cd backend
    npm install
  displayName: Install backend dependencies

# Frontend build
- script: |
    cd frontend
    npm run build
  displayName: Build frontend

# Docker build + push frontend
- task: Docker@2
  displayName: Build and Push Frontend Image
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'mihirkhaitan04/codesync-frontend'
    command: 'buildAndPush'
    Dockerfile: './frontend/Dockerfile'
    tags: |
      latest

# Docker build + push backend
- task: Docker@2
  displayName: Build and Push Backend Image
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'mihirkhaitan04/codesync-backend'
    command: 'buildAndPush'
    Dockerfile: './backend/Dockerfile'
    tags: |
      latest
